POST http://localhost:3010/product/add
Content-Type: application/json

{
    "label":"Smartphone iPhone",
    "brand":"Apple",
    "category":"Smart Phone",
    "price":1800.352
}

###
GET http://localhost:3010/product/all
###
GET http://localhost:3010/product/63cba8609e10103d2da2fdd6

###

PUT http://localhost:3010/product/63cba8609e10103d2da2fdd6
Content-Type: application/json

{
    "label":"Smart Phone Galxy S3 Samsung",
    "brand":"Sumsung",
    "category":"Smart Phone",
    "price":1000.352
}

###
DELETE  http://localhost:3010/product/63cba97ce6a3aff9360524c3