POST http://localhost:3010/product/add
Content-Type: application/json

{
    "label":"Smartphone iPhone X5",
    "brand":"Apple",
    "category":"Smart Phone",
    "price":1500.352
}

###
GET http://localhost:3010/product/all
###
GET http://localhost:3010/product/63cbad9d1c1bfb5bde1597c0

###

PUT http://localhost:3010/product/63cba8609e10103d2da2fdd6
Content-Type: application/json

{
    "label":"Smart Phone Galxy S2 Samsung",
    "brand":"Sumsung",
    "category":"SmartPhone",
    "price":1000.352
}

###
DELETE  http://localhost:3010/product/63cba97ce6a3aff9360524c3