POST http://localhost:3010/user/register
Content-Type: application/json

{
    "fullName":"Ala HELALI",
    "email":"ala@gmail.com",
    "password":"Toto2023"
}

###
POST http://localhost:3010/user/login
Content-Type: application/json

{
    "email":"helaliferid@gmail.com",
    "password":"Toto2023"
}

###
GET http://localhost:3010/user/all
x-access-token : eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyX2lkIjoiNjNjN2IzOWQ5YTAzMTdiNmQyOWJmOTVkIiwiZW1haWwiOiJoZWxhbGlmZXJpZEBnbWFpbC5jb20iLCJpYXQiOjE2NzQwMzgwNTIsImV4cCI6MTY3NDA0NTI1Mn0.xWfcu95nBPyHOJNh2WUcPuQ-e5Ws1zyvJpG2zoE_l5Q
