POST http://localhost:3010/user/register
Content-Type: application/json

{
    "fullName":"Salem",
    "email":"salem@hotmail.com",
    "password":"toto"
}

###
POST http://localhost:3010/user/login
Content-Type: application/json

{
    "email":"salem@gmail.com",
    "password":"toto"
}

###
GET http://localhost:3010/user/all
x-access-token : eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyX2lkIjoiNjNjN2IzOWQ5YTAzMTdiNmQyOWJmOTVkIiwiZW1haWwiOiJoZWxhbGlmZXJpZEBnbWFpbC5jb20iLCJpYXQiOjE2NzQ0NzY1NDAsImV4cCI6MTY3NDQ4Mzc0MH0.Z5s2VoOkqxXEe_m7Kk_gZ1D5-O67rMrankdqJC28HBk
